/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problemamochila;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class Resultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    int[][] mal;
    String[][] mtx;
    String[][] finlab;
    int iC;
    int pM;
    int []co;
    int[]Pesos;
    int[]valores;

    public Resultado(int[][] mal, String[][] mtx, int iC, int pM, int[] co, int[] Pesos, int[] valores) {
        this.mal = mal;
        this.mtx = mtx;
        this.iC = iC;
        this.pM = pM;
        this.co = co;
        this.Pesos = Pesos;
        this.valores = valores;
        initComponents();
    }


    public Resultado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnResumen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResul = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnResumen.setText("Resumen");
        btnResumen.setBackground(Color.BLACK);
        btnResumen.setForeground(Color.WHITE);
        btnResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenActionPerformed(evt);
            }
        });

        taResul.setColumns(25);
        taResul.setRows(5);
        taResul.setBackground(Color.BLACK);
        taResul.setForeground(Color.WHITE);
        taResul.setFont(new java.awt.Font("SansSerif BOLD", 4, 12));
        taResul.setBorder(BorderFactory.createLineBorder(Color.WHITE,2));
        jScrollPane2.setViewportView(taResul);
       
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(btnResumen)
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResumen)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenActionPerformed

        String desco=mtx[mtx.length-1][mtx[0].length-1];
        Resumen res = new Resumen(desco,Pesos);
        res.setLocationRelativeTo(null);
        res.setVisible(true);
    }//GEN-LAST:event_btnResumenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        DefaultTableModel model = (DefaultTableModel) tblResulta.getModel();
//        model.setRowCount(iC + 2);
//        model.setColumnCount(pM + 4);
        String s;
        finlab = new String [iC+2][pM+4];
        finlab[0][0] = "Articulo";
        finlab[0][1] = "Peso";
        finlab[0][2] = "Costo";
        for (int j = 3; j < pM + 4; j++) {
            finlab[0][j] = ""+(j-3)+"";
        }
        for (int i = 2; i<iC+2;i++){
            
            finlab[i][0]=String.valueOf(co[i-2]);
            finlab[i][1]=String.valueOf(Pesos[i-2]);
            finlab[i][2]=String.valueOf(valores[i-2]);
        }
        
        for(int i =1; i<iC+2;i++ ){
            for(int j = 3; j<pM+4;j++){
                finlab[i][j]=""+mal[i-1][j-3]+" ("+mtx[i-1][j-3]+")";
            }
        }
        
        
        for (int i = 0; i < iC+2; i++) {
            s="";
            for (int j = 0; j < pM+4; j++) {
                s+="" + finlab[i][j];
                s+="\t|\t";
            }
            taResul.append("\n"+s+"\n");
            
        }
        
//        for (int i = 0; i < iC+2; i++) {
//            System.out.println("");
//            for (int j = 0; j < pM+4; j++) {
//                System.out.print("\t" + finlab[i][j]);
//            }
//        }
        
        

//        for (int i = 0; i < iC + 2; i++) {
//            for (int j = 0; j < pM + 4; j++) {
//                tblResulta.setValueAt(finlab[i][j], i, j);
//            }
//        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResumen;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taResul;
    // End of variables declaration//GEN-END:variables
}
